name: Build Nuget Package X

env:
  PKG_VER: 1.2.11
  PKG_REV: ${{ github.run_number }}

  ZLIB_FNAME: zlib1211.zip
  #ZLIB_DNAME: zlib-${{ env.PKG_VER }}
  ZLIB_SHA256: d7510a8ee1918b7d0cad197a089c0a2cd4d6df05fee22389f67f115e738b178d

  VCVARSALL: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall'

defaults:
  run:
    shell: cmd

# manual and REST API runs only
on: workflow_dispatch

jobs:
  build-windows:
    name: Windows Build 
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download zLib
      run: curl --output ${{ env.ZLIB_FNAME }} https://zlib.net/${{ env.ZLIB_FNAME }}
    
    - name: Verify zLib Checksum
      run: 7z h -scrcSHA256 ${{ env.ZLIB_FNAME }} | findstr /C:"SHA256 for data" | call devops\check-sha256 "${{ env.ZLIB_SHA256 }}"

    - name: Extract zLib
      run: |
        7z x ${{ env.ZLIB_FNAME }}
        cd zlib-${{ env.PKG_VER }}

    - name: Patch Makefile.msc
      run: patch --input patches\Makefile.msc.patch win32\Makefile.msc

    - name: Copy license
      run: |
        mkdir ..\nuget\licenses
        copy zlib.h ..\nuget\licenses\zlib.h.txt

    - name: Copy header files
      run: |
        mkdir ..\nuget\build\native\include
        copy *.h ..\nuget\build\native\include\

    - name: VCVARSALL x86
      run: call "${{ env.VCVARSALL }}" x86

    - name: Build x86/Debug
      run: |
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI DEBUG=1
        call ..\devops\copy-config Win32 Debug
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI DEBUG=1 clean

    - name: Build x86/Release
      run: |
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI
        call ..\devops\copy-config Win32 Release
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI clean

    - name: VCVARSALL x64
      run: call "${{ env.VCVARSALL }}" x64

    - name: Build x64/Debug
      run: |
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI DEBUG=1
        call ..\devops\copy-config Win32 Debug
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI DEBUG=1 clean

    - name: Build x64/Release
      run: |
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI
        call ..\devops\copy-config Win32 Release
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI clean
    - name: Make Nuget package
      run: |
        nuget pack nuget\StoneSteps.zLib.Static.nuspec -Version ${{ env.PKG_VER }}.${{ env.PKG_REV }}
