name: Build Nuget Package X

env:
  PKG_VER: 1.2.11
  PKG_REV: ${{ github.run_number }}

  ZLIB_FNAME: zlib1211.zip
  #ZLIB_DNAME: zlib-${{ env.PKG_VER }}
  ZLIB_SHA256: d7510a8ee1918b7d0cad197a089c0a2cd4d6df05fee22389f67f115e738b178d

  VCVARSALL: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall'

defaults:
  run:
    shell: cmd

# manual and REST API runs only
on: workflow_dispatch

jobs:
  prep-zLib-source:
    name: Prepare zLib Source
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download zLib
      run: curl --output ${{ env.ZLIB_FNAME }} https://zlib.net/${{ env.ZLIB_FNAME }}
    
    - name: Verify zLib Checksum
      run: 7z h -scrcSHA256 ${{ env.ZLIB_FNAME }} | findstr /C:"SHA256 for data" | call devops\check-sha256 "${{ env.ZLIB_SHA256 }}"

    - name: Extract zLib
      run: |
        7z x ${{ env.ZLIB_FNAME }}

    - name: Patch Makefile.msc
      run: patch --unified --input patches\Makefile.msc.patch zlib-${{ env.PKG_VER }}\win32\Makefile.msc

    - name: Upload zLib Source
      uses: actions/upload-artifact@v2.2.1
      with:
        name: zlib-source
        path: zlib-${{ env.PKG_VER }}

  build-zLib:
    name: Build zLib
    needs: [prep-zLib-source]
    runs-on: windows-latest

    strategy:
      matrix:
       include:
         - platform: x64
           config: Debug
           vcvars: x64
           debug: DEBUG=1
         - platform: x64
           config: Release
           vcvars: x64
           debug: ''
         - platform: Win32
           config: Debug
           vcvars: x86
           debug: DEBUG=1
         - platform: Win32
           config: Release
           vcvars: x86
           debug: ''

    steps:
    - name: Download zLib Source
      uses: actions/download-artifact@v2.0.7
      with:
        name: zLib-source
        path: zlib-${{ env.PKG_VER }}

    - name: Build x86/Debug
      env:
        PLATFORM: ${{ matrix.platform }}
        CONFIG: ${{ matrix.config }}
        VCVARS: ${{ matrix.vcvars }}
        DEBUG: ${{ matrix.debug }}
        ZLIB_STATICLIB: zlib.lib
        ZLIB_STATICLIB_PDB: zlib.pdb
      working-directory: zlib-${{ env.PKG_VER }}
      run: |
        call "${{ env.VCVARSALL }}" %VCVARS%
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI %DEBUG%
        mkdir "..\nuget\build\native\lib\%PLATFORM%\%CONFIG%"
        copy /Y "%ZLIB_STATICLIB%" "..\nuget\build\native\lib\%PLATFORM%\%CONFIG%\"
        copy /Y "%ZLIB_STATICLIB_PDB%" "..\nuget\build\native\lib\%PLATFORM%\%CONFIG%\"
        nmake -f win32\Makefile.msc LOC=-DZLIB_WINAPI %DEBUG% clean

    - name: Upload zLib ${{ env.PLATFORM }}/${{ env.CONFIG }}
      uses: actions/upload-artifact@v2.2.1
      with:
        name: zlib-${{ env.PLATFORM }}-${{ env.CONFIG }}
        path: ..\nuget\build\native\lib\

  package-zLib:
    name: Package zLib
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy license
      working-directory: zlib-${{ env.PKG_VER }}
      run: |
        mkdir ..\nuget\licenses
        copy zlib.h ..\nuget\licenses\zlib.h.txt

    - name: Copy header files
      working-directory: zlib-${{ env.PKG_VER }}
      run: |
        mkdir ..\nuget\build\native\include
        copy *.h ..\nuget\build\native\include\

    - name: Download zLib x64/Debug
      uses: actions/download-artifact@v2.0.7
      with:
        name: zLib-x64-Debug
        path: ..\nuget\build\native\lib

    - name: Download zLib x64/Release
      uses: actions/download-artifact@v2.0.7
      with:
        name: zLib-x64-Release
        path: ..\nuget\build\native\lib

    - name: Download zLib Win32/Debug
      uses: actions/download-artifact@v2.0.7
      with:
        name: zLib-Win32-Debug
        path: ..\nuget\build\native\lib

    - name: Download zLib Win32/Release
      uses: actions/download-artifact@v2.0.7
      with:
        name: zLib-Win32-Release
        path: ..\nuget\build\native\lib

    - name: Make Nuget package
      run: |
        nuget pack nuget\StoneSteps.zLib.Static.nuspec -Version ${{ env.PKG_VER }}.${{ env.PKG_REV }}
